### ISSUE TITLE
Expose debug directory publicly

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/vfb-pipeline-collectdata#13]
For downloading debug files more easily, can we expose the [collect data volume](https://github.com/VirtualFlyBrain/vfb-pipeline-collectdata/blob/e7c9aa173b942d0557d5445c11063956c84331ff/Dockerfile#L4) the same way we expose the dumps pipeline (so we can access it with a browser)?

@Robbie1977

**Comment by Robbie1977** [comment]
http://virtualflybrain.org/data/VFB/OWL/out/
